### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by keeperofkeysAU**

### CODE REVIEW

**Comment by cartercheng** [comment]
Just needs a small change- remove the same delete from make spotless since it is redundant now.

**Comment by keeperofkeysAU** [comment]
i dunno tho, just quickly looking make spotless should still have it for
example... say you make some changes test the build then want to upload it
back to git wouldnt you just want to run make spotless rather than make
clean, then make spotless?

**Comment by keeperofkeysAU** [comment]
My Bad it includes clean sorry doing this on my mobile

**Comment by cartercheng** [comment]
Merged it in.

**Pull request merged**
